### PR TITLE
[New Feature] Implements email validator

### PR DESCRIPTION
**Pull request by alandev2**
# Description
I added another function to validate email, following the code standard.

Fixes # (Implementation)

# Checklist

- [X ] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [NO] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Hi @alandev2!

I'll add some tests, and then if everything is green we'll merge this to master and release a new version.

Thanks for the contribution!

**Comment by alandev2** [comment]
@FantasticFiasco Ok brother, thanks. 🚀

**Comment by FantasticFiasco** [comment]
Wow, are you still up? I just woke up here in Sweden, it's 7AM, but it must be in the middle of the night in Brazil?

I've added some test cases. They currently fail, some because I think you need replace `if (rg.test(` with `if (!rg.test(` (we currently throw the error when the format is correct), and some because the Regex doesn't accept the email addresses I added in the tests. Now, I don't even know if some of them are valid addresses, I copied them from https://gist.github.com/cjaoude/fd9910626629b53c4d25. Would it be possible for you to do a quick analysis whether it is the e-mail addresses that are invalid or the Regex that needs to be updated?

If not, please let me know and I'll look at the issue during the weekend.

**Comment by alandev2** [comment]
It's 3:25 😁 and I'm still going to work at 11 am haha

And... I'm going to review this problem now! :)

**Comment by FantasticFiasco** [comment]
Hell no! Go to sleep. You can fix this during the weekend. There is urge to rush this. Take your time.

**Comment by alandev2** [comment]
I like that, because I have to learn about 'tests and games' so there is no problem haha 🚀😁

**Comment by alandev2** [comment]
I test the code and it works, but when testing with the wire test, it broke. 🤔

i don't understand now 😐

**Comment by FantasticFiasco** [comment]
Did you forget to push? When I get latest one test still fail.

```
...
#toBeEmail
      ✕ should pass if expectation is fulfilled (2 ms)
      ✓ should fail if expectation is unfulfilled (8 ms)
```

**Comment by alandev2** [comment]
When i wake up i try to solve it again 😐 bye brother

**Comment by alandev2** [comment]
Now I can sleep in peace! 😁💙

**Comment by alandev2** [comment]
hey man, did you see the update?

**Comment by FantasticFiasco** [comment]
Sure did! Had some things to take care of today, I'll look at this tomorrow. Looked good though!

**Comment by FantasticFiasco** [comment]
Version 1.1.0 is now released on [npm](https://www.npmjs.com/package/@fantasticfiasco/expect).

Thank you so much for the contribution!

**Pull request merged**
